Added jail functionality fixes#10
ufosc/TERMINALMONOPOLY pull request #30
Opened 2024-10-03 06:03 UTC by Ossedda

Added jail functionality to the game. Players that land in jail are given a choice to roll for doubles or pay a $50 fine to get out of jail. Players that roll doubles get out of jail and move that amount of spaces according to their roll. Players that do not roll doubles three times in a row while in jail are forced to pay the $50 fine. Players that pay the fine are also not able to move the turn they pay, voluntary or not. Changes were made in player_class.py in order to accommodate players being in a jailed state.

2024-10-04 04:11 UTC, adamgulde commented on board.py
> +            10: Property(0, "Jail", -6, (32,2), COLORS.LIGHTGRAY, 0, 0, 0, 0, 0, 0, 0, 0, 0),
printing bug fixed

2024-10-04 04:11 UTC, adamgulde commented on board.py
> +            20: Property(0, "Free Parking", -8, (2,2), COLORS.LIGHTGRAY, 0, 0, 0, 0, 0, 0, 0, 0, 0),
should be identified as special code -8

2024-10-04 04:11 UTC, adamgulde commented on board.py
> -    def update_location(self, player:Player, roll: int, update_history, new = None) -> None:
changed this definition because update_history is used exclusively once.. makes more sense to hardcode in monopoly.py (see change there)

2024-10-04 04:12 UTC, adamgulde commented on monopoly.py
> +                        break
changed terminology and allow player to move after paying fine. this is typical monopoly gameplay

2024-10-04 04:12 UTC, adamgulde commented on monopoly.py
> +                    update_history(f"{players[turn].name} didn't roll doubles on their third turn. They paid $50 to post bail.")
terminology changes

2024-10-04 04:13 UTC, adamgulde commented on monopoly.py
> +                board.locations[10].players.append(turn)
relocated this to properly print after movement. looks better

2024-10-04 04:14 UTC, adamgulde commented
@Ossedda The last change I would like you to add is allowing a player to use a "get out of jail free" card. This is located in player_class and should be easy to implement. Test all cases sufficiently. Great work!

2024-10-04 04:15 UTC, adamgulde requested changes
see earlier comments :)

2024-10-04 10:08 UTC, Ossedda commented
> see earlier comments :)

Apologies on the initial jail logic. Second guessed myself on it :) 
Will look into the changes and adding Get Out of Jail Free Card usage

2024-10-15 00:40 UTC, adamgulde commented
@Ossedda update on this?

2024-11-15 19:20 UTC, closed without merging