Chance card movement bug fixes #16
ufosc/TERMINALMONOPOLY pull request #34
Opened 2024-10-04 05:48 UTC by RunDMC2

Fixed movement bug when landing on a chance or community chest space where player can't buy a space they land on when moved by a card

Fixed minor printing bug where space 10 and 7 printed at the same location

Fixed modularizing bug where cards.py needs but doesn't have access to update_history()

2024-10-05 20:13 UTC, adamgulde commented on .idea/.gitignore
please do not commit the .idea folder from your IDE

2024-10-05 20:14 UTC, adamgulde commented on board.py
nice catch!

2024-10-05 20:17 UTC, adamgulde requested changes
this seems to work from some testing I did, but at the moment will create conflicts because you did not push with the most recently updated code from main ufosc branch. Please see the new steps 3-6 for submitting changes from CONTRIBUTING.md. Following these guidelines will make review process much faster.

2024-10-06 20:24 UTC, RunDMC2 commented
just got rid of the .idea folder, and as for the code from the ufosc branch everything on my end says my fork is synced and my branch is up to date when I commit the changes I've made, let me know if any further changes need to be made

2024-10-08 17:04 UTC, adamgulde commented
> just got rid of the .idea folder, and as for the code from the ufosc branch everything on my end says my fork is synced and my branch is up to date when I commit the changes I've made, let me know if any further changes need to be made

ok weird- there's some stuff coming up when i look at the pr. can you come to cc today to look over this w me or send me your discord name?

2024-10-08 18:18 UTC, RunDMC2 commented
Yeah sounds good I'll be at cc today we can look over it

2024-10-08 22:37 UTC, RunDMC2 commented on monopoly.py
> +            if (players[turn].location + dice[0] + dice[1]) > 39:  # checks if player passed go
checks if player passes go only after they roll the dice

2024-10-08 22:38 UTC, RunDMC2 commented on monopoly.py
> +                        if old_loc > new_loc and new_loc != 10 and new_loc != players[turn].location - 3:  #check if chance card made player pass go
stores location before and after drawing a chance/community chest card, then compares the old and new locations to check if player has passed go

2024-10-11 03:03 UTC, adamgulde approved these changes
lgtm! great work :)

2024-10-11 03:03 UTC, merged