feat: Add Casino along with Blackjack and Coin Flip
ufosc/TERMINALMONOPOLY pull request #39
Opened 2024-10-15 05:05 UTC by jordanbrotherton

Adds a base casino.py module along with 2 modules in the casino_games package, blackjack.py and coin_flip.py. Resolves #32.

# casino.py
A casino file is now added, which is a central hub that loads games from the package casino_games. The games are loaded dynamically and should be fully handled by the casino file.

# casino_games
A new package is introduced, casino_games. This package should contain every game in the casino. As mentioned before, casino.py is responsible for playing these games. 

Each casino_game has a primary function that is called by casino.py, `play(player, active_terminal, bet)`. This primary function should return the new value of bet that should be added to the player's balance. Every casino_game should additionally have a game_title variable, as it is the name shown in the menu followed by the filename/command.

# blackjack.py
A singleplayer game of Blackjack is added, played against the house/dealer.  

Three outcomes can be obtained, "WIN" which returns double the bet, "LOSE" which returns 0, and "TIE" (stand-off) which returns the same amount the player bet.

# coin_flip.py
A coin flip game is added. The game is very simple and should be a good base of a casino_game.

Two outcomes can be obtained, double the bet with "WIN" if you land the side you picked and 0 with "LOSE" if you don't.

# player.py
Two modifications are made to the player.py file. The first is the addition of a `casino` command that initiates the casino.py module. The second is the renaming of the empty `balance()` function to `display_balance()` as it conflicts with the `balance` variable.

2024-10-17 21:37 UTC, adamgulde commented on casino_games/blackjack.py
> +    player.ss.print_screen()
changed these newlines bc it crashed on my computer

2024-10-17 21:39 UTC, adamgulde requested changes
this is really great! I just have a few comments I'll add throughout via comments

2024-10-17 21:40 UTC, adamgulde commented on casino_games/blackjack.py
> +    return bet
I believe it's appropriate to import screenspace here instead of calling it from player

2024-10-17 21:41 UTC, adamgulde commented on casino_games/blackjack.py
> +    return bet
naturally, replace all calls to player.ss.some_function with ss.some_function.. Also upstream with the latest push, print_screen is removed and taken care of by the better update_quadrant fxn.

2024-10-17 21:43 UTC, adamgulde commented on casino_games/blackjack.py
> +    return bet
likewise, you can 'from style import COLORS' or simply 'import style as s' because it is meant to be imported

2024-10-17 21:48 UTC, adamgulde commented on casino_games/coin_flip.py
> +    flip = random.randint(0,1)
using random.choice('heads', 'tails') might be a cleaner implementation

2024-10-17 21:51 UTC, adamgulde commented on casino_games/coin_flip.py
> +# BLACKJACK
OK to import screenspace as ss here as well, unless there was a distinct reason to not do so. lmk!

2024-10-17 21:52 UTC, adamgulde requested changes
see the comments left, and please rebase to the most recent push just bc it changes some important stuff. Overall I love how you implemented this and I'll very likely be using this as a template for other minigames

2024-10-17 21:55 UTC, adamgulde commented on casino_games/blackjack.py
> +status = ["                                                                           \n                                                                           \n     ██████           ████████████
also for large texts like this, instead of placing them in the code itself, either add it to the ascii.txt file in the root folder or add your own ascii.txt file into your casino_games directory

2024-10-21 21:54 UTC, jordanbrotherton commented on casino_games/coin_flip.py
> +# BLACKJACK
I ended up importing it. I had some concerns with importing from a parent package but it ended up working fine.

2024-10-21 21:55 UTC, jordanbrotherton commented on casino_games/coin_flip.py
> +    flip = random.randint(0,1)
I've changed it to make it more verbose instead of using magic numbers.

2024-10-21 21:56 UTC, jordanbrotherton commented on casino_games/blackjack.py
> +    return bet
I should have fixed this as well, no longer relying on player.py as heavily.

2024-10-21 21:57 UTC, jordanbrotherton commented on casino_games/blackjack.py
> +status = ["                                                                           \n                                                                           \n     ██████           ████████████
I've moved the big ASCII art (the results and coin flip assets) to ASCII.txt. The card_temp graphics aren't there though as the render_card functions uses a non-standard way of adding it.

2024-10-22 00:23 UTC, jordanbrotherton commented
I've updated the pull which should cover these change requests.

2024-10-22 02:10 UTC, adamgulde approved these changes
lgtm!

2024-10-22 02:13 UTC, merged